### ISSUE TITLE
I want to re-open my issue #74: making a guided process did not became any easier

### ISSUE THREAD

**Issue by HanneApers** [micado-eu/pa_application#131]
I tried to re-edit the guided process that I made end 2020, by deleting all the steps to make the graph again.
It was still as frustrating as it was back then, and I just gave up.
While adding steps, the graph just does it's own thing: it disappears; it is almost invisible; the steps don't align as I want them to align; when I think the steps are finally in the right order and I change something in text, the graph completely repositions itself, in a different and incorrect order. So after trying multiple times I stopped out of frustration. 
I don't get why my issue #74 was closed, as it is still not user-friendly and still frustrating to try and insert a guided process.

**Comment by gioppoluca** [comment]
It was closed because the problem that was written was solved.
Now the graph does not zoom reacting to the mouse scroll. We tested and the graph does not disappear adding new node.
Which browser are you using?
Thanks

**Comment by HanneApers** [comment]
Dear Luca,
Thanks for your answer.
I'm using Google Chrome on a laptop with a relatively small screen.
I'm sorry if I didn't write my first issue in an understandable way. The problem was not only that the graph zoomed in and out when scrolling. The overall process of introducing a guided process is not user-friendly, following are also issues in my opinion:
- the fact that you can't have a decent overview of the guided process while making it; if I want to see how my guided process looks like, I should go and check on the migrants app.
- using the 'graphic' tool is completely frustrating: now I inserted a rather 'easy' guided-process with only three steps following each other, and it was already difficult: the step I inserted first, did not remain the first step (on the visual graph) when I introduced the second one. For one reason or another, they switched places, I could not easily drag them in the right order. When I finally succeeded; the steps moved places every time again when I changed something in the text, if I inserted a next step, basically if I did something outside the graphic tool. Indicating the direction of the steps with arrows does not work properly either.
- the fact that you cannot easily edit the text (the text-editing here in GitHub is more straightforward, although also rather basic)
- the fact that it's not easy to insert images and place them wherever you want to make the description more visual; or using images instead of the boxes that represent the steps when showed in the migrants app, might be a way to make the guided process more visually understandable.

These are some issues I remember, I wanted to go and check again to be able to more elaborative on this, but when I log in on the pa app, all I get is an empty screen (I already retried multiple times in the last half hour). My internet seems to be working fine, so I guess that's not the cause. 

Thanks, Hanne.

**Comment by gioppoluca** [comment]
On the first bullet point I have to disagree: you have the flow on the side and that visualization will be fairly compliant with the one in the migrant.
In the end the graph is the same, I believe that the look and feel do not change how the process is strutured.
The order of the steps is managed by the arrow links so when you add the first step you have to give it a name and than add the second (do not worry on how they move in the side panel or worry on positioning them, just link the first to the second with the arrow they will position by themselves; positioning is not something that you have the control on.
On text editing you have to remember two things:
1) we need to write simple and concise text since it has to be consumed by the migrant on a smart phone
2) we need to send all the stuff to a translation tool and we cannot have complex formatted text for not having troubles in the end.

**Comment by HanneApers** [comment]
Dear Luca,

thanks for your answer.
I tried again by adding a complete new guided process on the same topic. 

I guess we will have to agree to disagree on that first point: I still don't think that it is clear how the flow will look like in the set-up of the process. Especially during the managing of the steps, and this is precisely because of the fact that, as you say, positioning is not something I have a control on. Which, for me, is very confusing and contradictory with the fact that this is the one of the most important aspects of inserting a guided process and intuitively, I want to be able to manage this. Now that I know it is not possible, I won't bother anymore, but in my opinion, every new user will be confused by this, so maybe a disclaimer or a kind of guidance how to manage the graphic tool then, would be helpful.

In relation to that: 'just linking' two steps with each other is not easy: when I want to select the first step and make an arrow to the second one, it very often drags the step around, and only after a few attempts I get to draw an arrow. No idea what I did different to succeed. I also tried by selecting the little square on top of the image of a step, that appears when scrolling over it, but it did not make a difference. 

I agree on what you say with the text editing, but for me it's related to the user-friendliness for who is inserting the guided process: the text font for the step description is very big and the text box itself rather small, which makes it difficult to see how your entire text looks like while writing it. Additionally there is no indication on how it will look like in the published version, for instance: there is no option to start a new line, only by 'entering' which starts a new alinea. This leaves a lot of white space in the end result and makes the sentences look like separate alinea's in the published version. 

While inserting the process again, I came across some extra difficulties:

- In my general description, for the section of 'generated documents' I could not choose the option 'other' or leave it open, it alwayse said 'field is required', although it is said that these options are possible when scrolling over the 'info' button. Only by first saving the general description and then opening it back up again to edit, I could save it without adding a 'generated document' and go on to managing the steps. 
- In the steps, I wanted to add documents, but could only choose from those fixed, and it is unclear to me where I can add a specific document myself, specific to that step. 
- As now the translation step is added before publication is possible, I can't check how the end-result of my inserted guided process looks like. Will there be a kind of 'pre-view' of the end result (how it wille appear on the migrant app) possible (which is related to my first points on the visual aspect and text-editing), so changes can still be made according to this end-result?

Thanks and kind regards,
Hanne
